# Generated by Django 4.0.4 on 2022-04-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(max_length=32)),
                ('category', models.TextField(max_length=1)),
                ('owner', models.TextField(max_length=16)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
