# Generated by Django 4.0.4 on 2022-04-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='file',
        ),
    ]
